# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-19 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0002_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='facebook',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='linkedin',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='telefon',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='twitter',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
