# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-22 17:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0003_auto_20190519_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='resum',
        ),
        migrations.AddField(
            model_name='noticia',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='noticia',
            name='seccio',
            field=models.CharField(choices=[('L', 'Local'), ('I', 'Internacional'), ('P', 'Pol\xedtica'), ('E', 'Economia'), ('S', 'Esports'), ('O', 'Opini\xf3'), ('A', 'Altres')], default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='noticia',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
